# Generated by Django 4.0.4 on 2022-04-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyPlayedTracks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_name", models.CharField(max_length=200)),
                ("artist_name", models.CharField(max_length=200)),
                ("played_at", models.CharField(max_length=200, unique=True)),
                ("timestamp", models.CharField(max_length=200)),
            ],
        ),
    ]
